### ISSUE TITLE
Add SRTP support

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_rtp_plugin#14]
RTSP development was started [there](https://github.com/membraneframework/membrane-element-rtp/pull/7) and should be continued either here or in a separate package that RTP plugin will have as an optional dependency. We may consider using [libsrtp](https://github.com/cisco/libsrtp). Adding SRTP may require some architectural changes during which we should keep as much processing as possible behind the SSRC router, to enhance distribution. We should also find a solution for sharing SRTP keys between different RTP and RTCP streams whenever necessary.

**Comment by mickel8** [comment]
done in #19
